apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimbus
  template:
    metadata:
      labels:
        app: nimbus
    spec:
      containers:
      - name: nimbus
        imagePullPolicy: Never
        image: nimbus2:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-service.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
      
---
apiVersion: v1
kind: Service
metadata:
  name: nimbus-service
spec:
  selector:
    app: nimbus
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
