apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-config-map1
    #namespace: {{ .Values.namespace }}
data:
  VARIABLE3: {{ .Values.var3_val }}

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-config-map2
    #namespace: {{ .Values.namespace }}
data:
  PYKAD_PORT: {{ .Values.app_port }}

