apiVersion: apps/v1
kind: Deployment
metadata:
  name: pykad
spec:
  selector:
    matchLabels:
      app: pykad
  template:
    metadata:
      labels:
        app: pykad
    spec:
      containers:
      - name: pykad
        image: nagaprashanth0006/pykad:latest
        env:
        - name: VARIABLE3
          value: "Value set from deployment.yml file"
        envFrom:
        - name: APP_PORT
          value: 7799
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7799
