apiVersion: apps/v1
kind: Deployment
metadata:
  name: pykad
spec:
  selector:
    matchLabels:
      app: pykad
  template:
    metadata:
      labels:
        app: pykad
    spec:
      containers:
      - name: pykad
        image: nagaprashanth0006/pykad:latest
        imagePullPolicy: Always
        command: ["python3"]
        args: ["/app/app.py", "param1=value1", "anotherParam", "lastOneYaar"]
        env:
        - name: VARIABLE3
          value: "Value set from deployment.yml file"
        - name: VARIABLE2
          valueFrom:
            secretKeyRef:
              name: pykad-secret1
              key: VAR2_SEC_VAL
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: pykad-config-map2
              key: PYKAD_PORT
        envFrom:
        - configMapRef:
            name: pykad-config-map1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        ports:
        - containerPort: 7798

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask1
spec:
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      volumes:
        - name: config-directory
          hostPath:
            path: "/mnt/C/Users/nagap/dev/k8s-pvc/config"
            #path: "C:\\Users\\nagap\\dev\\k8s-pvc\\config"
      containers:
      - name: flask1
        image: nagaprashanth0006/pykad:latest
        volumeMounts:
          - mountPath: "/app/configs"
            name: config-directory
        imagePullPolicy: Always
        command: ["python3"]
        args: ["/app/app.py", "role=FlaskApp"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        ports:
        - containerPort: 7799
