apiVersion: apps/v1
kind: Deployment
metadata:
  name: pykad
spec:
  selector:
    matchLabels:
      app: pykad
  template:
    metadata:
      labels:
        app: pykad
    spec:
      containers:
      - name: pykad
        image: nagaprashanth0006/pykad:latest
        env:
        - name: VARIABLE3
          value: "Value set from deployment.yml file"
        - name: VARIABLE2
          valueFrom:
            secretKeyRef:
              name: pykad-secret1
              key: VAR2_SEC_VAL
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: pykad-config-map2
              key: PYKAD_PORT
        envFrom:
        - configMapRef:
            name: pykad-config-map1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7799
