apiVersion: v1
kind: Service
metadata:
  name: pykad
spec:
  type: NodePort
  selector:
    app: pykad
  ports:
  - port: 7798
    targetPort: 7798
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: flask1
spec:
  type: NodePort
  selector:
    app: flask1
  ports:
  - port: 7799
    targetPort: 7799
    nodePort: 30002
